/*
# [Create Contact Messages Table]
This migration creates a new table `contact_messages` to store submissions from the website's contact form. It includes columns for the sender's name, email, subject, and message content.

## Query Description: [This operation creates a new table for storing contact form submissions. It has no impact on existing data as it's a new, isolated table. It is a safe, structural change.]

## Metadata:
- Schema-Category: "Structural"
- Impact-Level: "Low"
- Requires-Backup: false
- Reversible: true (Can be dropped)

## Structure Details:
- Table: `public.contact_messages`
- Columns: `id`, `created_at`, `name`, `email`, `subject`, `message`

## Security Implications:
- RLS Status: Enabled
- Policy Changes: Yes, a new policy is added.
- Auth Requirements: Allows anonymous users to insert data.

## Performance Impact:
- Indexes: A primary key index is added on `id`.
- Triggers: None
- Estimated Impact: Negligible performance impact.
*/

-- 1. Create the table
CREATE TABLE public.contact_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name text,
    email text,
    subject text,
    message text
);

-- 2. Enable Row Level Security
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

-- 3. Add a policy to allow anonymous inserts
CREATE POLICY "Allow anonymous inserts" ON public.contact_messages
FOR INSERT TO anon
WITH CHECK (true);
